remote_theme: pmarsceill/just-the-docs
title: Dandelion Docs
description : An Efficient And Fully Automated Approach To Sample Chemical Reaction Space
url : "https://mhyeok1.github.io/dand_docs/"
logo : "docs/dandelion.svg"



defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      nav_order: 1

aux_links:
  "Dandelion on GitHub":
    - "//github.com/mhyeok1/dand"

back_to_top: true
back_to_top_text: "Back to top"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2023 Minhyeok Lee. Distributed by an <a href=\"https://raw.githubusercontent.com/mhyeok1/dand/refs/heads/main/LICENSE\">MIT license.</a>"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/mhyeok1/dand_docs" # the github URL for your repo
gh_edit_branch: "docs" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

