remote_theme: pmarsceill/just-the-docs
title: Dandelion Docs
description : An Efficient And Fully Automated Approach To Sample Chemical Reaction Space
url : "https://mhyeok1.github.io/dand_docs/"
logo : "docs/dandelion.svg"



defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      nav_order: 1

aux_links:
  "Dandelion on GitHub":
    - "//github.com/mhyeok1/dand"

nav_external_links:
  - title: Dandelion on GitHub
    url: https://github.com/mhyeok1/dand
    hide_icon: false
    opens_in_new_tab: false

sass:
  load_paths:
    - _sass

extras_scss:
    - "_sass/custom/custom.scss"

back_to_top: true
back_to_top_text: "Back to top"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/mhyeok1/dand_docs" # the github URL for your repo
gh_edit_branch: "docs" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

