remote_theme: pmarsceill/just-the-docs
title: Dandelion Docs
description : An Efficient And Fully Automated Approach To Sample Chemical Reaction Space
url : "https://mhyeok1.github.io/dand_docs/"
logo : "docs/dandelion.svg"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      nav_order: 1

aux_links:
  "Dandelion on GitHub":
    - "//github.com/mhyeok1/dand"
